"use node";

import { v } from "convex/values";
import { internalAction } from "./_generated/server";
import { internal } from "./_generated/api";
import { requestJson } from "./lib/anthropic";
import {
  validateMoviePoolBatch,
  type MoviePoolEntry,
} from "./lib/validators";

// Pool is generated by *category* (not tier) per the user's curation spec.
// Target audience: Gen Z (born ~2000-2005). 1995-2024, weighted heavily 2005-2020.
// Each entry self-tags its tier (mass_appeal | well_known | cult_classic).
// Total target: ~100 movies.
type Category = {
  name: string;
  count: number;
  description: string;
};

const CATEGORIES: Category[] = [
  {
    name: "animated",
    count: 25,
    description:
      "Animated films from Pixar, DreamWorks, Disney, Illumination, Sony Animation. Examples of the *kind* of titles to draw from (use these as a guide, not a hard list): Shrek series, Finding Nemo, Ratatouille, Up, Wall-E, Toy Story trilogy, Monsters Inc, Kung Fu Panda, Madagascar, Despicable Me, Frozen, Moana, Tangled, Coco, Inside Out, How to Train Your Dragon, The Incredibles, Megamind, Cars, Spider-Verse, Encanto, Zootopia, Lilo & Stitch.",
  },
  {
    name: "marvel_mcu",
    count: 10,
    description:
      "Marvel Cinematic Universe entries that are culturally massive: Iron Man, The Avengers, Infinity War, Endgame, Black Panther, Guardians of the Galaxy, Thor Ragnarok, Spider-Man Homecoming, Spider-Man No Way Home, Doctor Strange, Captain America Winter Soldier.",
  },
  {
    name: "dc",
    count: 6,
    description:
      "DC films Gen Z knows: The Dark Knight, The Dark Knight Rises, Joker (2019), Wonder Woman, Aquaman, The Batman (2022), Man of Steel.",
  },
  {
    name: "ya_fantasy",
    count: 12,
    description:
      "Young-adult fantasy/sci-fi franchises Gen Z grew up with: Harry Potter films, Hunger Games series, Twilight series, Maze Runner, Divergent, Percy Jackson, Narnia.",
  },
  {
    name: "teen_coming_of_age",
    count: 12,
    description:
      "Teen comedies and coming-of-age hits: Mean Girls, Superbad, Easy A, 21 Jump Street, Pitch Perfect, Project X, The Hangover, Step Brothers, Talladega Nights, Napoleon Dynamite, Juno, Lady Bird, Booksmart.",
  },
  {
    name: "horror",
    count: 8,
    description:
      "Modern horror that crossed into mainstream: Get Out, Us, Hereditary, It (2017), A Quiet Place, The Conjuring, Scream (2022), Midsommar, Smile.",
  },
  {
    name: "disney_channel_nostalgia",
    count: 6,
    description:
      "Disney Channel / family live-action nostalgia for elder Gen Z: High School Musical, Camp Rock, Princess Diaries, Holes, Matilda, The Parent Trap (1998).",
  },
  {
    name: "action_blockbuster",
    count: 15,
    description:
      "Action and blockbuster tentpoles: Pirates of the Caribbean (Curse of the Black Pearl, Dead Man's Chest), Fast & Furious entries (Fast Five, Furious 7), John Wick, Mission Impossible Fallout, Top Gun Maverick, Inception, Interstellar, The Matrix, Avatar, Avatar Way of Water, Jurassic Park, Jurassic World, Transformers, Mad Max Fury Road.",
  },
  {
    name: "certified_genz_hits",
    count: 6,
    description:
      "Acclaimed standalone films that became Gen Z social-media touchstones: Parasite, Whiplash, La La Land, The Social Network, Knives Out, Everything Everywhere All At Once.",
  },
];

export const generatePool = internalAction({
  args: { dryRun: v.optional(v.boolean()) },
  handler: async (ctx, args) => {
    const seenTitles = new Set<string>();
    const all: MoviePoolEntry[] = [];
    const perCategory: Record<string, number> = {};

    for (const cat of CATEGORIES) {
      const existingList = Array.from(seenTitles).slice(0, 200).join(", ");
      const userMessage = [
        `Generate exactly ${cat.count} curated movies for the "${cat.name}" category of a daily movie-guessing game.`,
        "",
        `Target audience: Gen Z casual movie watchers (born ~2000-2005). They grew up with these movies on Disney Channel/Netflix, saw them in theaters as kids/teens, or saw them go viral on TikTok. NOT film-school cinephiles.`,
        "",
        `Category: ${cat.description}`,
        "",
        "Hard constraints:",
        "- Each movie must be universally recognizable to people born ~2000-2005.",
        "- Visually distinctive: must have iconic shots/colors/scenes recognizable from a single frame.",
        "- Year between 1995 and 2024, weighted heavily toward 2005-2020.",
        "- No obscure indie films, no pre-1995 classics, no foreign films UNLESS they hit massive Western popularity (e.g., Parasite, Spirited Away).",
        '- "year" is the original theatrical release year (number, e.g. 2019).',
        '- "aliases" is a list of common alternate spellings/abbreviations and the title without leading "The/A/An". Use [] if none.',
        '- "genres" is 1-3 lowercase tags from: action, adventure, animation, comedy, crime, documentary, drama, family, fantasy, history, horror, musical, mystery, romance, sci-fi, sport, thriller, war, western.',
        '- "tier" is one of: "mass_appeal" (basically every Gen Z person knows it), "well_known" (most Gen Z film fans know it), "cult_classic" (devoted Gen Z fanbase but not universal). Tag honestly per movie.',
        existingList
          ? `- Do NOT repeat any of these already-included titles: ${existingList}`
          : "",
        "",
        "Reply with ONLY a JSON array, no prose, no markdown fences. Schema:",
        '[{ "title": string, "aliases": string[], "year": number, "tier": "mass_appeal"|"well_known"|"cult_classic", "genres": string[] }]',
      ]
        .filter(Boolean)
        .join("\n");

      const batch = await requestJson(
        {
          system:
            "You are a film curator helping build a movie-guessing game targeted at Gen Z casual viewers. Reply only in valid JSON matching the requested schema.",
          userMessage,
          maxTokens: 8000,
          temperature: 0.4,
        },
        validateMoviePoolBatch,
      );

      let added = 0;
      for (const entry of batch) {
        const key = entry.title.toLowerCase();
        if (seenTitles.has(key)) continue;
        seenTitles.add(key);
        all.push(entry);
        added++;
      }
      perCategory[cat.name] = added;
    }

    if (args.dryRun) {
      return { inserted: 0, perCategory, total: all.length };
    }

    const inserted: number = await ctx.runMutation(
      internal.moviePoolDb.insertPoolEntries,
      { entries: all },
    );
    return { inserted, perCategory, total: all.length };
  },
});
