import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const popularityTier = v.union(
  v.literal("mass_appeal"),
  v.literal("well_known"),
  v.literal("cult_classic"),
);

const hintType = v.union(
  v.literal("emoji"),
  v.literal("plot_summary"),
  v.literal("famous_quote"),
  v.literal("cast_clue"),
  v.literal("crew_clue"),
  v.literal("fake_review"),
  v.literal("object_list"),
  v.literal("tagline"),
  v.literal("first_or_last_line"),
  v.literal("setting"),
  v.literal("soundtrack"),
  v.literal("trivia"),
);

const hint = v.object({
  type: hintType,
  content: v.string(),
  order: v.number(),
});

export default defineSchema({
  // Curated pool of candidate movies. Generated upfront via Claude;
  // daily cron picks from here.
  moviePool: defineTable({
    title: v.string(),
    aliases: v.array(v.string()),
    year: v.number(),
    tier: popularityTier,
    genres: v.array(v.string()),
    used: v.boolean(),
    usedOnDate: v.optional(v.string()),
  })
    .index("by_used", ["used"])
    .index("by_tier_used", ["tier", "used"]),

  // The puzzle for a given UTC date. Generated by daily cron.
  dailyPuzzles: defineTable({
    date: v.string(),
    movieTitle: v.string(),
    movieAliases: v.array(v.string()),
    moviePoolId: v.id("moviePool"),
    hints: v.array(hint),
    releasedAt: v.number(),
    // Set after the webhook fires for this puzzle. Prevents double-posting
    // on cron retries.
    announcedAt: v.optional(v.number()),
  }).index("by_date", ["date"]),

  // One per (user, date). Tracks the player's run.
  attempts: defineTable({
    userId: v.string(),
    guildId: v.optional(v.string()),
    puzzleDate: v.string(),
    hintsRevealed: v.number(),
    guessed: v.boolean(),
    correct: v.boolean(),
    score: v.number(),
    grid: v.array(
      v.union(
        v.literal("correct"),
        v.literal("wrong"),
        v.literal("revealed"),
        v.literal("unseen"),
      ),
    ),
    completedAt: v.optional(v.number()),
  })
    .index("by_user_date", ["userId", "puzzleDate"])
    .index("by_date", ["puzzleDate"])
    .index("by_guild_date", ["guildId", "puzzleDate"]),

  // Aggregate per-player stats.
  players: defineTable({
    userId: v.string(),
    // Last-seen Discord username; refreshed on each completed game so the
    // leaderboard shows a real handle instead of a snowflake id.
    username: v.optional(v.string()),
    totalScore: v.number(),
    currentStreak: v.number(),
    longestStreak: v.number(),
    gamesPlayed: v.number(),
    lastPlayedDate: v.optional(v.string()),
  })
    .index("by_user", ["userId"])
    .index("by_total_score", ["totalScore"]),
});
